after_success:
  - ./scripts/auto-deploy.sh

env:
  global:
    - secure: "Kx5zpsbE+bVVdF25IyqHxafm1KnPuFp3qWLXWEj2PtaX9L4ZCYy0nL1QLjTvzleuy/nyCsT/diqaqJGvcMrLXSEuSpmXgKDasBhbCMIoZVrVKCIMOwEYS+cP7OctSIWwMyCWI/pjJiL8F/Qlw509eB9dcuPnWRgboghWSlCwnoI="

language: node_js

node_js:
  - "5"
