after_success:
  - ./scripts/auto-deploy.sh

env:
  global:
    - secure: "yVoOyz6X+fxFq+tYjIJcCDuvZPLN08c/IDu0rVshc4DXWuulMfLOa824aiiz2JcTLfHapJrku5U/LEVfIUKAzh/2OieqCoxlRir2fMXIrqQmqUgu76/CSEdD2A1e9DlWypIDANYtNjUlfxkOPpKqObYofCPTIW0lo2LMKv7P3oztdePMIYPWl5CaW7heko2tSp8N4Xk14mVaCYpg4ww3fpQqH29qSnXaISlDWh1+8QWdGV90FsSSVYyqq1kgp09ckXFKnneLe8QCiGWIS2JfrkJy2bK8arz6u4nTbnSqNpZ6IyfU+5hBozV5suDljMBtGFF9z9WJQjek1XA+/2432W9vCRjBHmHhEFKySq0riNzyf1yQEYJd4rFKo6/pdg8tFuE2GG4BpM4HlVe6rPKrPlnZRjn7QDKassxhQ+BKTVLKyTk0RQcblUxP5oyfJ0bGAD7gkP2U9SZtXWdwE049xi4Ul5fZMbWNV0NzdETwAeXzeo1bLiEu3w6xidXz7dsyynzOgLoKelD5UjYIZV9+jU7f2mJ33IWNO+67biznKl4dmJUnvz87OedduCUQtAHAGb0RYP88JPEHglMRWqpLWGbrA4e30HiEBAw/GsXJM+tRv1ENj48kweOFX3brF4h5Q2ONdNpzs+XbcFGTFZDlnqku8RbXR0Agronmrh3voew="

language: node_js

node_js:
  - "5"
